movie/imovie/urls.py
from django.conf.urls import url, patterns, include
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.base import TemplateView
from rest_framework.urlpatterns import format_suffix_patterns
from forms import ActorForm, MovieForm, DirectorForm
from models import Director, Movie, Actor,\
					MovieReview, MovieCategory, Review
from views import MovieDetail, ActorDetail, reviewM,\
					DirectorDetail, ActorListAPI, ActorDetailAPI,\
					ActorCreate, ActorDelete, MovieDelete, MovieCreate,\
					DirectorDelete, DirectorCreate, DirectorListAPI, \
					DirectorDetailAPI, MovieListAPI, MovieDetailAPI


urlpatterns = [

	# Home page
	url(r'^$', TemplateView.as_view(template_name="principal.html"), name="Principal"),

	# Movies list
	url(r'^movie/$', ListView.as_view(
			queryset=Movie.objects.filter().order_by('user')[:5],
			context_object_name='latest_movie_list',
			template_name='movie/movie_list.html'),
		name='movie_list'),

	# Movies detail
	url(r'^movie/(?P<pk>\d+)/$', MovieDetail.as_view(
			model=Movie,
			template_name='movie/movie_detail.html'),
		name='movie_detail'),

	# Movie create
	url(r'^movie/create/$', MovieCreate.as_view(), name='movie_create'),

	# Movie edit
	url(r'^movie/(?P<pk>\d+)/edit/$', UpdateView.as_view(
		model=Movie,
		template_name='form.html',
		form_class=MovieForm),
		name='movie_edit'),

	# Movie delete
	url(r'^movie/(?P<pk>\d+)/delete/$', MovieDelete, name='movie_delete'),

	url(r'^movie/(?P<pk>\d+)/reviews/create/$', reviewM,
		name='review_movie_create'),


	# Actor list
	url(r'^actor/$', ListView.as_view(
			queryset=Actor.objects.filter().order_by('user')[:5],
			context_object_name='latest_actor_list',
			template_name='actor/actor_list.html'),
		name='actor_list'),

	# Actor detail
	url(r'^actor/(?P<pk>\d+)/$', ActorDetail.as_view(
			model=Actor,
			template_name='actor/actor_detail.html'),
		name='actor_detail'),

	# Actor create
	url(r'^actor/create/$', ActorCreate.as_view(),
		name='actor_create'),

	# Actor edit
	url(r'^actor/(?P<pk>\d+)/edit/$', UpdateView.as_view(
		model=Actor,
		template_name='form.html',
		form_class=ActorForm),
		name='actor_edit'),

	# Actor delete
	url(r'^actor/(?P<pk>\d+)/delete/$', ActorDelete,
		name='actor_delete'),

	# Director list
	url(r'^director/$', ListView.as_view(
			queryset=Director.objects.filter().order_by('user')[:5],
			context_object_name='latest_director_list',
			template_name='director/director_list.html'),
		name='director_list'),

	# Director detail
	url(r'^director/(?P<pk>\d+)/$', DirectorDetail.as_view(
			model=Director,
			template_name='director/director_detail.html'),
		name='director_detail'),

	# Director create
	url(r'^director/create/$', DirectorCreate.as_view(), name='director_create'),

	# Director edit
	url(r'^director/(?P<pk>\d+)/edit/$', UpdateView.as_view(
		model=Director,
		template_name='form.html',
		form_class=DirectorForm),
		name='director_edit'),

	# Director delete
	url(r'^director/(?P<pk>\d+)/delete/$', DirectorDelete, name='director_delete'),



	# RESTful API
	url(r'^api/actor/$',ActorListAPI.as_view(), name='actor-list'),
	url(r'^api/actor/(?P<pk>\d+)/$', ActorDetailAPI.as_view(), name='actor-detail'),

	url(r'^api/director/$',DirectorListAPI.as_view(), name='director-list'),
	url(r'^api/director/(?P<pk>\d+)/$', DirectorDetailAPI.as_view(), name='director-detail'),

	url(r'^api/movie/$',MovieListAPI.as_view(), name='movie-list'),
	url(r'^api/movie/(?P<pk>\d+)/$', MovieDetailAPI.as_view(), name='movie-detail'),

]

# Format	suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])


#	Default	login/logout	views
urlpatterns += patterns('', url(r'^api-auth/', include('rest_framework.urls', namespace = 'rest_framework'))
)

movie/movie/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^', include('imovie.urls', namespace='imovie')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^imovie/', include('imovie.urls', namespace='imovie')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

movie/imovie/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date


class Director(models.Model):
	name = models.TextField()
	birthday = models.DateField()
	biography = models.TextField(blank=True, null=True)
	user = models.ForeignKey(User, default=1)

	def __unicode__(self):
		return u"%s" % self.name

	def get_absolute_url(self):
		return reverse('imovie:director_detail', kwargs={'pk': self.pk})


class Actor(models.Model):
	name = models.TextField()
	birthday = models.DateField()
	biography = models.TextField(blank=True, null=True)
	city = models.TextField(max_length=50, null= True)
	country = models.TextField(max_length=50, null= True)
	state = models.TextField(max_length=50, null= True)
	user = models.ForeignKey(User, default=1)

	def __unicode__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('imovie:actor_detail', kwargs={'pk': self.pk})


class Category(models.Model):
	CATEGORY_CHOICES = ((0, 'Undefined'), (1, 'Thriller'), (2, 'Comedy'), (3, 'Terror'), (4, 'Action'), (5, 'Romantic'), (6, 'Adventure'),
		(7, 'Sci-fi'), (8, 'Drama'), (9, 'Western'), (10, 'Animation'))
	category = models.PositiveSmallIntegerField('Category', blank=False, default=0, choices=CATEGORY_CHOICES)
	user = models.ForeignKey(User, default=1)


class Review(models.Model):
    ''' Review atributes '''
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)


class Movie(models.Model):
	name = models.TextField()
	year = models.IntegerField()
	overview = models.TextField(blank=True, null=True)
	user = models.ForeignKey(User, default=1)
	director = models.ForeignKey(Director)
	actors = models.ManyToManyField(Actor)

	def __unicode__(self):
		return self.name

	def averageRating(self):
		reviewCount = self.moviereview_set.count()
		if not reviewCount:
			return 0
		else:
			ratingSum = sum([float(review.rating) for review in self.moviereview_set.all()])
			return ratingSum / reviewCount

	def get_absolute_url(self):
		return reverse('imovie:movie_detail', kwargs={'pk': self.pk})


class MovieReview(Review):
	movie = models.ForeignKey(Movie)


class MovieCategory(Category):
	movie = models.ForeignKey(Movie, related_name="cat")

movie/imovie/forms.py
from django.forms import ModelForm
from models import Actor, Director, Movie


class ActorForm(ModelForm):
    class Meta:
        model = Actor
        fields = "__all__"
        exclude = ('user',)

class DirectorForm(ModelForm):
    class Meta:
        model = Director
        fields = "__all__"
        exclude = ('user',)

class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"
        exclude = ('user',)

movie/imovie/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from models import MovieReview, Movie, Actor, Director, MovieCategory
from forms import ActorForm, MovieForm, DirectorForm
from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse
from rest_framework.response import Response
from serializers import ActorSerializer, MovieSerializer, DirectorSerializer



class MovieDetail(DetailView):
	model = Movie
	template_name = 'movie/movie_detail.html'

	def get_context_data(self, **kwargs):
		context = super(MovieDetail, self).get_context_data(**kwargs)
		context['RATING_CHOICES'] = MovieReview.RATING_CHOICES
		return context

class MovieCreate(CreateView):
	''' Create Movie, use template form.html '''
	model = Movie
	template_name = 'form.html'
	form_class = MovieForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(MovieCreate, self).form_valid(form)

def MovieDelete(request, pk):
	'''Movie delete'''
	movie = get_object_or_404(Movie, pk=pk)
	movie.delete()
	return HttpResponseRedirect(reverse('imovie:movie_list', ))


class ActorDetail(DetailView):
	model = Actor
	template_name = 'actor/actor_detail.html'
	def get_context_data(self, **kwargs):
		context = super(ActorDetail, self).get_context_data(**kwargs)
		return context


class ActorCreate(CreateView):
	''' Create Actor, use template form.html '''
	model = Actor
	template_name = 'form.html'
	form_class = ActorForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(ActorCreate, self).form_valid(form)

def ActorDelete(request, pk):
	'''Actor delete'''
	actor = get_object_or_404(Actor, pk=pk)
	actor.delete()
	return HttpResponseRedirect(reverse('imovie:actor_list', ))


class DirectorDetail(DetailView):
	model = Director
	template_name = 'director/director_detail.html'


class DirectorCreate(CreateView):
	''' Create Director, use template form.html '''
	model = Director
	template_name = 'form.html'
	form_class = DirectorForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(DirectorCreate, self).form_valid(form)

def DirectorDelete(request, pk):
	'''Director delete'''
	director = get_object_or_404(Director, pk=pk)
	director.delete()
	return HttpResponseRedirect(reverse('imovie:director_list', ))

def category(request, pk):
	movie = get_object_or_404(Movie, pk=pk)
	category = MovieCategory(
		rating=request.POST['rating'],
		user=request.user,
		movie=movie)
	category.save()
	return HttpResponseRedirect(reverse('imovie:movie_detail', args=(movie.id,ea)))

def reviewM(request, pk):
	movie = get_object_or_404(Movie, pk=pk)
	reviews = MovieReview(
		rating=request.POST['rating'],
		comment=request.POST['comment'],
		user=request.user,
		movie=movie)
	reviews.save()
	return HttpResponseRedirect(reverse('imovie:movie_detail', args=(movie.id,)))


@api_view(['GET'])
def api_root(request, format=None):
    """
    The	entry endpoint of our API.
    """
    return Response({
        'actor': reverse('actor-list', request=request),
    })


class ActorListAPI(generics.ListCreateAPIView):
    """
    API	endpoint that represents a list	of	actor.
    """
    model = Actor
    queryset = Actor.objects.all()
    serializer_class = ActorSerializer


class ActorDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    """
    API	endpoint that represents a single actor.
    """
    model = Actor
    queryset = Actor.objects.all()
    serializer_class = ActorSerializer

class MovieListAPI(generics.ListCreateAPIView):
    """
    API	endpoint that represents a list	of	actor.
    """
    model = Movie
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


class MovieDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    """
    API	endpoint that represents a single actor.
    """
    model = Movie
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

class DirectorListAPI(generics.ListCreateAPIView):
    """
    API	endpoint that represents a list	of	movie.
    """
    model = Director
    queryset = Director.objects.all()
    serializer_class = DirectorSerializer


class DirectorDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    """
    API	endpoint that represents a single director.
    """
    model = Director
    queryset = Director.objects.all()
    serializer_class = DirectorSerializer

movie/imovie/templates/movie/movie_detail.html
{% extends "base.html" %}
{%  block  title  %}Movie -{{movie.name  }}{%  endblock  %}
{% block content %}
<span vocab="http://schema.org/Movie" typeof="Movie">
  <h1>
    <span property="name">{{ movie.title }}</span>
  	{{ movie.name }}
      (<a  href="{%  url  'imovie:movie_edit'  movie.id  %}">edit</a>)
      (<a  href="{%  url  'imovie:movie_delete'  movie.id  %}">delete</a>)
  </h1>

<div id="sidebar">
    {% block sidebar %}<ul><li><a href="/imovie">Home</a></li></ul>{% endblock %}
</div>

<p>
	<year><span property="year"> Year: {{ movie.year }} </span></year>  <br />
	<overview><span property="overview"> Overview: {{ movie.overview }} </span></overview>  <br />
	<director><span property="director"> Director: {{ movie.director }} </span></director> <br />
	<actors>Actors:
		{% for actor in movie.actors.all %}
			<li><a href="../../actor/{{actor.id}}">
				{{ actor.name }}</a></li>
		{% endfor %}
	</actors>  <br />


  <h2>Reviews</h2>
  <span rel="aggregateRating">
      <p typeof="AggregateRating">
      <span property="ratingValue">{{ movie.averageRating|stringformat:".1f" }}</span>
      {% with movie.moviereview_set.all|length as reviewCount %}
      out of 5 stars
      </br>
      <span property="reviewCount">{{ reviewCount }} reviews from users</span>
      {% endwith %}
      </p>
  </span>
  <span rel="Review">
    <ul typeof="Review">
          {%  for  review  in  movie.moviereview_set.all  %}
          <li property="Review">

                  <p><span property="Comments">{{  review.comment  }}</span></p>
                  <span property="worstRating" content="1"></span>
                  <p><span property="valueRating">{{  review.rating  }} </span> star{{  review.rating|pluralize  }}</p>
                  <span property="bestRating" content="5"></span>
                  <p>Created  by  {{  review.user  }}  on  {{  review.date  }}</p>
              </li>
          {%  endfor  %}
      </ul>
  </span>
          <h3>Add Review</h3>
          {%  if  user.is_authenticated  %}
              <form  action="{%  url  'imovie:review_movie_create'  movie.id  %}"  method="post">
              {%  csrf_token  %}
                  Message:  <textarea  name="comment"  id="comment"  rows="4"></textarea>
                  <p>Rating:</p>
                  <p>{%  for  rate  in  RATING_CHOICES  %}
                      <input  type="radio"  name="rating"  id="rating{{  forloop.counter  }}"  value="{{  rate.0}}"  />
                      <label  for="choice{{  forloop.counter  }}">{{  rate.1}}  star{{  rate.0|pluralize  }}</label>
                      <br/>
                  {%  endfor  %}
                  </p>
              <input  type="submit"  value="Review"  />
              </form>
            </span>
          {% else %}
              <p>Please, log in first</p>
  {% endif %}



<a  href="/imovie/movie">Return to Movies</a>
{% endblock %}

movie/imovie/templates/movie/movie_list.html
{% extends "base.html" %}
{% block content %}
<div id="sidebar">
    {% block sidebar %}<ul><li><a href="/imovie">Home</a></li></ul>{% endblock %}
</div>
<h1>
	Movies
  {%  if  user.is_authenticated %}
    (<a  href="{%  url  'imovie:movie_create'  %}">add</a>)
  {% endif %}
</h1>
<u1>
	{% for movie in latest_movie_list %}
		<li><a href="./{{movie.id}}">
			{{ movie.name }}</a></li>
	{% empty %}<li>Sorry, no movies registered yet.</li>
	{% endfor %}
</u1>
{% endblock %}