movie/imovie/urls.py
from django.conf.urls import url, patterns, include
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.base import TemplateView
from rest_framework.urlpatterns import format_suffix_patterns
from forms import ActorForm, MovieForm, DirectorForm
from models import Director, Movie, Actor,\
					MovieReview, MovieCategory, Review
from views import MovieDetail, ActorDetail, reviewM,\
					DirectorDetail, ActorListAPI, ActorDetailAPI,\
					ActorCreate, ActorDelete, MovieDelete, MovieCreate,\
					DirectorDelete, DirectorCreate, DirectorListAPI, \
					DirectorDetailAPI, MovieListAPI, MovieDetailAPI


urlpatterns = [

	# Home page
	url(r'^$', TemplateView.as_view(template_name="principal.html"), name="Principal"),

	# Movies list
	url(r'^movie/$', ListView.as_view(
			queryset=Movie.objects.filter().order_by('user')[:5],
			context_object_name='latest_movie_list',
			template_name='movie/movie_list.html'),
		name='movie_list'),

	# Movies detail
	url(r'^movie/(?P<pk>\d+)/$', MovieDetail.as_view(
			model=Movie,
			template_name='movie/movie_detail.html'),
		name='movie_detail'),

	# Movie create
	url(r'^movie/create/$', MovieCreate.as_view(), name='movie_create'),

	# Movie edit
	url(r'^movie/(?P<pk>\d+)/edit/$', UpdateView.as_view(
		model=Movie,
		template_name='form.html',
		form_class=MovieForm),
		name='movie_edit'),

	# Movie delete
	url(r'^movie/(?P<pk>\d+)/delete/$', MovieDelete, name='movie_delete'),

	url(r'^movie/(?P<pk>\d+)/reviews/create/$', reviewM,
		name='review_movie_create'),


	# Actor list
	url(r'^actor/$', ListView.as_view(
			queryset=Actor.objects.filter().order_by('user')[:5],
			context_object_name='latest_actor_list',
			template_name='actor/actor_list.html'),
		name='actor_list'),

	# Actor detail
	url(r'^actor/(?P<pk>\d+)/$', ActorDetail.as_view(
			model=Actor,
			template_name='actor/actor_detail.html'),
		name='actor_detail'),

	# Actor create
	url(r'^actor/create/$', ActorCreate.as_view(),
		name='actor_create'),

	# Actor edit
	url(r'^actor/(?P<pk>\d+)/edit/$', UpdateView.as_view(
		model=Actor,
		template_name='form.html',
		form_class=ActorForm),
		name='actor_edit'),

	# Actor delete
	url(r'^actor/(?P<pk>\d+)/delete/$', ActorDelete,
		name='actor_delete'),

	# Director list
	url(r'^director/$', ListView.as_view(
			queryset=Director.objects.filter().order_by('user')[:5],
			context_object_name='latest_director_list',
			template_name='director/director_list.html'),
		name='director_list'),

	# Director detail
	url(r'^director/(?P<pk>\d+)/$', DirectorDetail.as_view(
			model=Director,
			template_name='director/director_detail.html'),
		name='director_detail'),

	# Director create
	url(r'^director/create/$', DirectorCreate.as_view(), name='director_create'),

	# Director edit
	url(r'^director/(?P<pk>\d+)/edit/$', UpdateView.as_view(
		model=Director,
		template_name='form.html',
		form_class=DirectorForm),
		name='director_edit'),

	# Director delete
	url(r'^director/(?P<pk>\d+)/delete/$', DirectorDelete, name='director_delete'),



	# RESTful API
	url(r'^api/actor/$',ActorListAPI.as_view(), name='actor-list'),
	url(r'^api/actor/(?P<pk>\d+)/$', ActorDetailAPI.as_view(), name='actor-detail'),

	url(r'^api/director/$',DirectorListAPI.as_view(), name='director-list'),
	url(r'^api/director/(?P<pk>\d+)/$', DirectorDetailAPI.as_view(), name='director-detail'),

	url(r'^api/movie/$',MovieListAPI.as_view(), name='movie-list'),
	url(r'^api/movie/(?P<pk>\d+)/$', MovieDetailAPI.as_view(), name='movie-detail'),

]

# Format	suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])


#	Default	login/logout	views
urlpatterns += patterns('', url(r'^api-auth/', include('rest_framework.urls', namespace = 'rest_framework'))
)

movie/movie/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^', include('imovie.urls', namespace='imovie')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^imovie/', include('imovie.urls', namespace='imovie')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
]

movie/imovie/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date


class Director(models.Model):
	name = models.TextField()
	birthday = models.DateField()
	biography = models.TextField(blank=True, null=True)
	user = models.ForeignKey(User, default=1)

	def __unicode__(self):
		return u"%s" % self.name

	def get_absolute_url(self):
		return reverse('imovie:director_detail', kwargs={'pk': self.pk})


class Actor(models.Model):
	name = models.TextField()
	birthday = models.DateField()
	biography = models.TextField(blank=True, null=True)
	city = models.TextField(max_length=50, null= True)
	country = models.TextField(max_length=50, null= True)
	state = models.TextField(max_length=50, null= True)
	user = models.ForeignKey(User, default=1)

	def __unicode__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('imovie:actor_detail', kwargs={'pk': self.pk})


class Category(models.Model):
	CATEGORY_CHOICES = ((0, 'Undefined'), (1, 'Thriller'), (2, 'Comedy'), (3, 'Terror'), (4, 'Action'), (5, 'Romantic'), (6, 'Adventure'),
		(7, 'Sci-fi'), (8, 'Drama'), (9, 'Western'), (10, 'Animation'))
	category = models.PositiveSmallIntegerField('Category', blank=False, default=0, choices=CATEGORY_CHOICES)
	user = models.ForeignKey(User, default=1)


class Review(models.Model):
    ''' Review atributes '''
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)


class Movie(models.Model):
	name = models.TextField()
	year = models.IntegerField()
	overview = models.TextField(blank=True, null=True)
	user = models.ForeignKey(User, default=1)
	director = models.ForeignKey(Director)
	actors = models.ManyToManyField(Actor)

	def __unicode__(self):
		return self.name

	def averageRating(self):
		reviewCount = self.moviereview_set.count()
		if not reviewCount:
			return 0
		else:
			ratingSum = sum([float(review.rating) for review in self.moviereview_set.all()])
			return ratingSum / reviewCount

	def get_absolute_url(self):
		return reverse('imovie:movie_detail', kwargs={'pk': self.pk})


class MovieReview(Review):
	movie = models.ForeignKey(Movie)


class MovieCategory(Category):
	movie = models.ForeignKey(Movie, related_name="cat")

movie/imovie/forms.py
from django.forms import ModelForm
from models import Actor, Director, Movie


class ActorForm(ModelForm):
    class Meta:
        model = Actor
        fields = "__all__"
        exclude = ('user',)

class DirectorForm(ModelForm):
    class Meta:
        model = Director
        fields = "__all__"
        exclude = ('user',)

class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"
        exclude = ('user',)

movie/imovie/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from models import MovieReview, Movie, Actor, Director, MovieCategory
from forms import ActorForm, MovieForm, DirectorForm
from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse
from rest_framework.response import Response
from serializers import ActorSerializer, MovieSerializer, DirectorSerializer



class MovieDetail(DetailView):
	model = Movie
	template_name = 'movie/movie_detail.html'

	def get_context_data(self, **kwargs):
		context = super(MovieDetail, self).get_context_data(**kwargs)
		context['RATING_CHOICES'] = MovieReview.RATING_CHOICES
		return context

class MovieCreate(CreateView):
	''' Create Movie, use template form.html '''
	model = Movie
	template_name = 'form.html'
	form_class = MovieForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(MovieCreate, self).form_valid(form)

def MovieDelete(request, pk):
	'''Movie delete'''
	movie = get_object_or_404(Movie, pk=pk)
	movie.delete()
	return HttpResponseRedirect(reverse('imovie:movie_list', ))


class ActorDetail(DetailView):
	model = Actor
	template_name = 'actor/actor_detail.html'
	def get_context_data(self, **kwargs):
		context = super(ActorDetail, self).get_context_data(**kwargs)
		return context


class ActorCreate(CreateView):
	''' Create Actor, use template form.html '''
	model = Actor
	template_name = 'form.html'
	form_class = ActorForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(ActorCreate, self).form_valid(form)

def ActorDelete(request, pk):
	'''Actor delete'''
	actor = get_object_or_404(Actor, pk=pk)
	actor.delete()
	return HttpResponseRedirect(reverse('imovie:actor_list', ))


class DirectorDetail(DetailView):
	model = Director
	template_name = 'director/director_detail.html'


class DirectorCreate(CreateView):
	''' Create Director, use template form.html '''
	model = Director
	template_name = 'form.html'
	form_class = DirectorForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(DirectorCreate, self).form_valid(form)

def DirectorDelete(request, pk):
	'''Director delete'''
	director = get_object_or_404(Director, pk=pk)
	director.delete()
	return HttpResponseRedirect(reverse('imovie:director_list', ))

def category(request, pk):
	movie = get_object_or_404(Movie, pk=pk)
	category = MovieCategory(
		rating=request.POST['rating'],
		user=request.user,
		movie=movie)
	category.save()
	return HttpResponseRedirect(reverse('imovie:movie_detail', args=(movie.id,ea)))

def reviewM(request, pk):
	movie = get_object_or_404(Movie, pk=pk)
	reviews = MovieReview(
		rating=request.POST['rating'],
		comment=request.POST['comment'],
		user=request.user,
		movie=movie)
	reviews.save()
	return HttpResponseRedirect(reverse('imovie:movie_detail', args=(movie.id,)))


@api_view(['GET'])
def api_root(request, format=None):
    """
    The	entry endpoint of our API.
    """
    return Response({
        'actor': reverse('actor-list', request=request),
    })


class ActorListAPI(generics.ListCreateAPIView):
    """
    API	endpoint that represents a list	of	actor.
    """
    model = Actor
    queryset = Actor.objects.all()
    serializer_class = ActorSerializer


class ActorDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    """
    API	endpoint that represents a single actor.
    """
    model = Actor
    queryset = Actor.objects.all()
    serializer_class = ActorSerializer

class MovieListAPI(generics.ListCreateAPIView):
    """
    API	endpoint that represents a list	of	actor.
    """
    model = Movie
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


class MovieDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    """
    API	endpoint that represents a single actor.
    """
    model = Movie
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

class DirectorListAPI(generics.ListCreateAPIView):
    """
    API	endpoint that represents a list	of	movie.
    """
    model = Director
    queryset = Director.objects.all()
    serializer_class = DirectorSerializer


class DirectorDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    """
    API	endpoint that represents a single director.
    """
    model = Director
    queryset = Director.objects.all()
    serializer_class = DirectorSerializer

movie/imovie/templates/base.html
{%  load  staticfiles  %}
<!DOCTYPE  html>
<html  lang="en">
<head>
    <link  rel="stylesheet"  href="{%  static  "style/base.css"  %}"  />
    <title>{%  block  title  %}Movies{%  endblock  %}</title>

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"/>
    <script	src="http://code.jquery.com/jquery-2.2.3.js"></script>
    <script	src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
</head>
<body>
    <div  id="header">
    {%  block  header  %}
    {%  if  user.username  %}
        <p>User:  {{  user.username  }}  |  <a  href="{%  url  'logout'  %}?next={{request.path}}">logout</a>
        </p>
    {%  else  %}
        <p><a  href="{%  url  'login'  %}?next={{request.path}}">login</a></p>
    {%  endif  %}
    {%  endblock  %}
    </div>
    <div  id="content">
    {%  block  content  %}
    {%  if  error_message  %}
        <p>
            <strong>{{  error_message  }}</strong>
        </p>
    {%  endif  %}
    {%  endblock  %}
    </div>
    <div  id="footer">
        {%  block  footer  %}

        {%  endblock  %}
    </div>
</body>
</html>

movie/imovie/templates/form.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<script>
         $(function() {
            $.getJSON("{% static "countries.json" %}", {}, function (countries) {
                $("#id_country").autocomplete({
                    source: countries
                });
            });
            $("#id_city").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "demo"
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_state").val(ui.item.stateOrProvince);
                        $("#id_country").val(ui.item.countryName);
                    }
                }
            });
        });
    </script>
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

movie/imovie/templates/principal.html
{% extends "base.html" %}
{% block content %}
<h1>
    Home Page
</h1>
<ul>
  <li><a href="actor/">
      Actors list</a></li>
  <li><a href="director/">
      Directors list</a></li>
  <li><a href="movie/">
      Movies list</a></li>
</ul>
<p>David Calavia -- Mireia Moix -- Judith Villanueva </p>
{% endblock %}